### PR TITLE
Output meta information to stderr

### PR DESCRIPTION
**Pull request by cjuner**
This way, relevant information can be more easily processed when being piped
into other programs.

This also applies to a file newly introduced in https://github.com/VIISON/scs-commander/pull/11. So merge that first.

### CODE REVIEW

**Review by svenmuennich — CHANGES_REQUESTED** [review]
Good one! It looks like you've missed some `console.log()`s though. Can you please double check?

**Comment by cjuner** [comment]
@svenmuennich To be honest, for some subcommands I found it hard to conceive what exactly someone might want to process when piping into another command.

Most remaining `console.log`s are in compability.js and upload.js and I'm not really sure, how to handle these. I'd suggest we only change them further when we find a specific use case.

**Comment by svenmuennich** [comment]
Well, but what about [this instance then](https://github.com/VIISON/scs-commander/pull/12/files#diff-103cd10caf496d601d4c0fd9f3f0db2bR118)? I'd assume that that's actually the information someone would want to get when piping the output of the `compatibility` command.

**Comment by cjuner** [comment]
Changed as requested in https://github.com/VIISON/scs-commander/pull/12#issuecomment-370733996.

Remember to **`git rebase --autosquash`** before merging.

**Review by svenmuennich — APPROVED** [review]

**Pull request merged**
